### ISSUE TITLE
Copy & paste of code not working

### ISSUE THREAD

**Issue by Rossi1337** [WilliamKarolDiCioccio/open_local_ui#17]
When the response contains code snipptets or code references these are formatted. This is nice. But you cannot select the code parts to copy from the code.

**Comment by WilliamKarolDiCioccio** [comment]
It's I problem I've been facing since the beginning and still don't know how to get around it. Give me the time to recover some resources I found on the problem, I'll leave the links here

**Comment by WilliamKarolDiCioccio** [comment]
This [issue](https://github.com/git-touch/highlight.dart/pull/25) from the highlight.dart repository (one of the subpackages of flutter_highlighter, the one responsible for the problem) shows that there is a pull request to add the functionality waiting for approval since long ago. Now, I found a [fork](https://github.com/Izubrr/highlight.dart) from a user that seems to be implementing the changes. I forked it on my [own](https://github.com/WilliamKarolDiCioccio/highlight.dart) and I'm testing it in the new [branch](https://github.com/WilliamKarolDiCioccio/open_local_ui/tree/fix-highlight.dart). If you want you too can experiment with it

**Comment by WilliamKarolDiCioccio** [comment]
I almost destroyed the entire tree 😨! Tomorrow I'll finish fixing other small problems related to markdown code widget and merge

**Comment by WilliamKarolDiCioccio** [comment]
@Rossi1337 If you can do some research on text selection across widgets as my fix doesn't cover this issue therefore we cannot select code and other text as a single text block but rather we have to do it separately

**Comment by WilliamKarolDiCioccio** [comment]
Fixed the issue and correctly added submodule. Closing this as complete and opening #22
